// import type { Metadata } from 'next'
// import { Geist, Geist_Mono } from 'next/font/google'
// import './globals.css'
// import QueryProvider from '@/providers/query-provider'

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// })

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <QueryProvider>{children}</QueryProvider>
//       </body>
//     </html>
//   )
// }

import type { Metadata } from 'next'
import { Inter, Poppins , Roboto } from 'next/font/google'
import './globals.css'
import ReactQueryProvider from '@/providers/query-provider'


import { toast, Toaster } from "sonner";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  variable: "--font-roboto",
  display: "swap",
})

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-poppins',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable}  ${poppins.variable} ${roboto.variable}     font-poppins  font-roboto `}>
        <ReactQueryProvider>
        <Toaster
  position='top-center'
  richColors 
  toastOptions={{
    style: {
      width: "auto",
      maxWidth: 'auto',
      whiteSpace: "pre-wrap",
    },
    className: 'lg:max-w-[calc(100vw-2rem)] max-w-md',
  }} 
/>
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  )
}
